### ISSUE TITLE
Sony Xperia ZR2 Compact  - Pixel IMS stops 

### ISSUE THREAD

**Issue by i998** [kyujin-cho/pixel-volte-patch#273]
**Disclaimer**
Sorry to taking your attention to non-pixel phone.  However there are a number of threads on XDA that illustrates that your beatiful Pixel IMS works on other handsets too  - Sonyy Readme etc.  Hence I am asking for a help. Would be possible for you to help with troubleshooting why the Pixel IMS suddenly stops?

**Describe the bug**
Sony Xperia ZR2 Compact  - Pixel IMS stops.  

**To Reproduce**
1. Follow the instruction step by step up as published at  https://github.com/kyujin-cho/pixel-volte-patch/blob/main/README.en.md
up to "Tap "Allow all the time" when seeing prompt asking for Shizuku permission."  I.e. get shizuku running, Pixel IMS installed, all good, no issues.
3. Tap "Allow all the time" 
4. See error: the phone have a pop-up saying: 
    Pixel IMS keeps stopping
          - app info
          - close app

Any further attempt to restart the application ends up with the same error message as above.

**Expected behavior**
Pixel IMS continue to work or provides a description/log what went wrong and why it stops 

**Screenshots**
N/A 

**Desktop (please complete the following information):**
 - OS: Win 7 SP1
 - ADB platform-tools_r34.0.4-windows  (latest for Win 7)

**Smartphone (please complete the following information):**
 - Device: Sony Xperia XZ2 Compact , H8324
 - OS: Android 10 
 - Firmware: H8324_Customized AU_52.1.A.3.49-R4C

**Additional context**
Mobile Network : Internode 
APN Vodafone live! live.vodafone.com
Phone / SIM are not locked

**Comment by fillwithjoy1** [comment]
grab adb logcat and dump it here

**Comment by i998** [comment]
P.S. Please also see  results from  
_adb logcat -b radio_  

[logcatRadio.txt](https://github.com/kyujin-cho/pixel-volte-patch/files/14445962/logcatRadio.txt)

**Comment by bolabola6789** [comment]
Seems like a bug with Android 10 devices. I have a secondary phone running Android 10 too and faced this issue

**Comment by i998** [comment]
Is any chance to fix this bug?  Unfortunately Sony does not have any further update with a higher Androind version or a patch....

**Comment by torbol** [comment]
Here it's mine with exactly the same error:

Device: Huawei P30 Pro
OS: Android 10


The logcat says:

`03-12 00:50:13.060  5086  5086 E AndroidRuntime: FATAL EXCEPTION: main
03-12 00:50:13.060  5086  5086 E AndroidRuntime: Process: dev.bluehouse.enablevolte, PID: 5086
03-12 00:50:13.060  5086  5086 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/telephony/TelephonyFrameworkInitializer;
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.Moder.getSub(Moder.kt:72)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.CarrierModer.getSubscriptions(Moder.kt:87)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt.PixelIMSApp$loadApplication(HomeActivity.kt:133)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt.access$PixelIMSApp$loadApplication(HomeActivity.kt:1)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt$PixelIMSApp$1.invoke(HomeActivity.kt:156)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt$PixelIMSApp$1.invoke(HomeActivity.kt:154)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.ComponentsKt$OnLifecycleEvent$1$1$observer$1.onStateChanged(Components.kt:69)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.View.dispatchAttachedToWindow(View.java:20107)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3619)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2549)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:911)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:900)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
03-12 00:50:13.060  5086  5086 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyFrameworkInitializer
03-12 00:50:13.060  5086  5086 E AndroidRuntime:        ... 34 more
`

The problems seems related with the library used in Moder.kt: [import android.telephony.TelephonyFrameworkInitializer](https://github.com/kyujin-cho/pixel-volte-patch/blob/a944bd127c88066403a9a5e3c897bac989cb8eb7/app/src/main/java/dev/bluehouse/enablevolte/Moder.kt#L11C1-L11C55) maybe as @bolabola6789 mentioned, it's not compatible with Android 10, or maybe the sdk used is too recent for us [API level 34 I think (Android 14).](https://developer.android.com/guide/topics/manifest/uses-sdk-element?hl=es-419#ApiLevels) I'm not familiar with programming at this level, just starting in this world, but who knows, this comment might help to another in something.

**Comment by fillwithjoy1** [comment]
> Here it's mine with exactly the same error:
> 
> Device: Huawei P30 Pro OS: Android 10
> 
> The logcat says:
> 
> ```
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime: FATAL EXCEPTION: main
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime: Process: dev.bluehouse.enablevolte, PID: 5086
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/telephony/TelephonyFrameworkInitializer;
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.Moder.getSub(Moder.kt:72)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.CarrierModer.getSubscriptions(Moder.kt:87)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt.PixelIMSApp$loadApplication(HomeActivity.kt:133)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt.access$PixelIMSApp$loadApplication(HomeActivity.kt:1)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt$PixelIMSApp$1.invoke(HomeActivity.kt:156)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.HomeActivityKt$PixelIMSApp$1.invoke(HomeActivity.kt:154)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at dev.bluehouse.enablevolte.ComponentsKt$OnLifecycleEvent$1$1$observer$1.onStateChanged(Components.kt:69)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.View.dispatchAttachedToWindow(View.java:20107)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3619)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3626)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2549)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2166)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8887)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1280)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer.doFrame(Choreographer.java:911)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:900)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:103)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:219)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8668)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyFrameworkInitializer
> 03-12 00:50:13.060  5086  5086 E AndroidRuntime:        ... 34 more
> ```
> 
> The problem seems related to the library used in Moder.kt: [import android.telephony.TelephonyFrameworkInitializer](https://github.com/kyujin-cho/pixel-volte-patch/blob/a944bd127c88066403a9a5e3c897bac989cb8eb7/app/src/main/java/dev/bluehouse/enablevolte/Moder.kt#L11C1-L11C55) maybe as @bolabola6789 mentioned, it's not compatible with Android 10 (but the minimum SDK in Google play is 29 which is just for Android 10) I'm not familiar with programming at this level, just starting in this world, but who knows, this comment might help to another in something.

You might be onto something

**Comment by raphinesse** [comment]
Same issue on a OnePlus 5T using Android 10.
