### ISSUE TITLE
Crashing when allowing Pixel IMS to access Shizuku (Android 10)

### ISSUE THREAD

**Issue by A-Constipated-Cow** [kyujin-cho/pixel-volte-patch#320]
As the title states, Pixel IMS crashes whenever I click on "Allow all the time"  when shizuku is running. App functions without shizuku but can't apply patch without it. My phone is running android 10.

**Comment by Zinx2022** [comment]
Hi @kyujin-cho, 
Shizuku Version: 13.5,adb
Pixel IMS Version: 1.28
Android Version: 10

I am experiencing the same issue as the comment from @A-Constipated-Cow, I've tried to do some debugging but I'm too newbie to work it out. 
It may be a similar problem to https://github.com/kyujin-cho/pixel-volte-patch/issues/225 but specifically to Android 10, after Shizuku is enabled, opening Pixel LMS will automatically crash. If you disable Shizuku, Pixel LMS does not crash. 

SDK-29 that was recently downgraded in the Android Manifest from SDK 30 -> 29 (on https://github.com/kyujin-cho/pixel-volte-patch/compare/main...feature/lower-min-sdk) allowing support for Android 10s. Perhaps there are dependent libraries that has not been made compatible with Android 10. 

Note, Pixel LMS doesn't crash on phones running on Android 11+

Thx

**Comment by A-Constipated-Cow** [comment]
Don't know if this helps but I ran Pixel IMS with logcat and this seems to be whats causing the crash:
![image](https://github.com/user-attachments/assets/06bc5212-166d-438a-84b5-46116854cf27)

As it says at the bottom Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyFrameworkInitializer

**Comment by lunzima** [comment]
I'm experiencing same issue here with Unihertz Titan.

**Comment by karashata** [comment]
Same issue here, Nokia 7 Plus running Android 10.

**Comment by Shinkoku** [comment]
Same, Note 9 Android 10
Dev would you pls take a look at this issue?

**Comment by czh1019** [comment]
Same issue here， huawei p30pro,Android 10

**Comment by ismaelmatoso** [comment]
Same here, Huawei P40 Lite - EMUI 12

**Comment by spvkgn** [comment]
```
--------- beginning of main
01-24 20:58:21.648 16741 16741 E use.enablevolt: Not starting debugger since process cannot load the jdwp agent.
01-24 20:58:21.689 16741 16741 I Perf    : Connecting to perf service.
01-24 20:58:21.702 16741 16741 D ShizukuProvider: Initialize Sui: false
01-24 20:58:21.705 16741 16757 D ShizukuProvider: binder received
01-24 20:58:21.705 16741 16758 D ShizukuProvider: binder received
01-24 20:58:21.707 16741 16757 I ShizukuApplication: attachApplication
01-24 20:58:21.869 16741 16741 D HomeActivity:Home: Shizuku granted
01-24 20:58:21.869 16741 16741 D AndroidRuntime: Shutting down VM
--------- beginning of crash
01-24 20:58:21.870 16741 16741 E AndroidRuntime: FATAL EXCEPTION: main
01-24 20:58:21.870 16741 16741 E AndroidRuntime: Process: dev.bluehouse.enablevolte, PID: 16741
01-24 20:58:21.870 16741 16741 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/telephony/TelephonyFrameworkInitializer;
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at dev.bluehouse.enablevolte.Moder.getSub(Moder.kt:72)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at dev.bluehouse.enablevolte.CarrierModer.getSubscriptions(Moder.kt:87)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at dev.bluehouse.enablevolte.HomeActivityKt.PixelIMSApp$loadApplication(HomeActivity.kt:133)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at dev.bluehouse.enablevolte.HomeActivityKt.access$PixelIMSApp$loadApplication(HomeActivity.kt:1)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at dev.bluehouse.enablevolte.HomeActivityKt$PixelIMSApp$1.invoke(HomeActivity.kt:156)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at dev.bluehouse.enablevolte.HomeActivityKt$PixelIMSApp$1.invoke(HomeActivity.kt:154)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at dev.bluehouse.enablevolte.ComponentsKt$OnLifecycleEvent$1$1$observer$1.onStateChanged(Components.kt:69)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.kt:251)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.kt:287)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:199)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:20110)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2054)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1747)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7793)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:798)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7458)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
01-24 20:58:21.870 16741 16741 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.telephony.TelephonyFrameworkInitializer
01-24 20:58:21.870 16741 16741 E AndroidRuntime: 	... 34 more
01-24 20:58:26.711 16741 16753 I use.enablevolt: WaitForGcToComplete blocked CollectorTransition on ProfileSaver for 11.581ms
01-24 20:58:31.336 16741 16741 I Process : Sending signal. PID: 16741 SIG: 9
```

**Comment by Sybawayh** [comment]
Same issue here : Oppo A5 (2020) cph1931 - Android 10

**Comment by yjcn** [comment]
@Sybawayh @spvkgn @karashata @Shinkoku @lunzima @czh1019 @Zinx2022 @A-Constipated-Cow I checked the Android 10 API and made some modifications. Now it runs normally on my Huawei Mate 20 Pro, but it didn’t successfully enable vowifi. I guess it might be related to Huawei. Please test it on your devices, and I look forward to your feedback!
the apk is here https://github.com/yjcn/pixel-volte-patch/releases/tag/v0.6.2

**Comment by yjcn** [comment]
> [@Sybawayh](https://github.com/Sybawayh) [@spvkgn](https://github.com/spvkgn) [@karashata](https://github.com/karashata) [@Shinkoku](https://github.com/Shinkoku) [@lunzima](https://github.com/lunzima) [@czh1019](https://github.com/czh1019) [@Zinx2022](https://github.com/Zinx2022) [@A-Constipated-Cow](https://github.com/A-Constipated-Cow) I checked the Android 10 API and made some modifications. Now it runs normally on my Huawei Mate 20 Pro, but it didn’t successfully enable vowifi. I guess it might be related to Huawei. Please test it on your devices, and I look forward to your feedback! the apk is here https://github.com/yjcn/pixel-volte-patch/releases/tag/v0.6.2

Before testing, please uninstall the old version and then install the new one, as the APK signature has changed.
@ismaelmatoso

**Comment by karashata** [comment]
I can confirm the modified app runs properly now on my Nokia 7 Plus. I am able to toggle both VoLTE and VoWiFi, though IMS status shows as unregistered and neither actually work. I am unsure if this is because my device is outright incompatible with my carrier's network or if it's due to how the carrier allows or blocks devices it doesn't officially support (notably my carrier only officially supports devices sold in my country). I do not expect help with this issue, but it is good to at least know the issue preventing the app from even running has been fixed.

**Comment by yjcn** [comment]
> I can confirm the modified app runs properly now on my Nokia 7 Plus. I am able to toggle both VoLTE and VoWiFi, though IMS status shows as unregistered and neither actually work. I am unsure if this is because my device is outright incompatible with my carrier's network or if it's due to how the carrier allows or blocks devices it doesn't officially support (notably my carrier only officially supports devices sold in my country). I do not expect help with this issue, but it is good to at least know the issue preventing the app from even running has been fixed.

@karashata First of all, thank you very much for your feedback. I only replaced the APIs to a lower version, and I’m not very familiar with some of the lower-level reasons. Indeed, whether volte or vowifi can be enabled also depends on the carrier, so we’ll just have to wait for others’ feedback.

**Comment by ismaelmatoso** [comment]
> > [@Sybawayh](https://github.com/Sybawayh) [@spvkgn](https://github.com/spvkgn) [@karashata](https://github.com/karashata) [@Shinkoku](https://github.com/Shinkoku) [@lunzima](https://github.com/lunzima) [@czh1019](https://github.com/czh1019) [@Zinx2022](https://github.com/Zinx2022) [@A-Constipated-Cow](https://github.com/A-Constipated-Cow) I checked the Android 10 API and made some modifications. Now it runs normally on my Huawei Mate 20 Pro, but it didn’t successfully enable vowifi. I guess it might be related to Huawei. Please test it on your devices, and I look forward to your feedback! the apk is here https://github.com/yjcn/pixel-volte-patch/releases/tag/v0.6.2
> 
> Before testing, please uninstall the old version and then install the new one, as the APK signature has changed. [@ismaelmatoso](https://github.com/ismaelmatoso)

Can also atest that on my Huawei P40 Lite it now opens without crashing, but although it appears as Registered the functions appear to be merely cosmetic, because it doesn't change, for the good, either VoLTE (which I was able to brute force through my Courrier SIM Card app) or VoWiFi (Which appears as ON/Active on every setting but doesn't work at all, even tested today).

Thank you for the hassle, I hope it works for someone, surely!

**Comment by chrisre2cn** [comment]
@yjcn 
I have tested v0.6.2 on 2 android 10 phones. One is a ZTE SD845 phone and volte actually worked ( APP made volte switch visible and then IMS registered ). Another phone is a huawei P20, the APP made volte swith visible however IMS remain unregistered.

Hope this information helps and the future version can work on huawei phones as well.

**Comment by chrisre2cn** [comment]
Another update for v0.6.2: on the ZTE SD845 phone, volte switch disappeared after reboot. Needed to run pixel ims again to enable the switch and volte.

**Comment by elbasty25jan** [comment]
@yjcn 

huawei mate 20 pro 

I have tried the updated app it's ok and gives the required info within the first page, however it's crashed upon select the SIM card. 

please advise

**Comment by frank7345349587** [comment]
Pixel p20 pro on fizz. I report that your modded pixel ims work on my device and i just passed the test call successfully. I now have vowifi and  volte working. Thanks!

**Comment by basq2** [comment]
Sony XZ2 Compact latest stock Android 10. I have tried this version and running, it detects Shizuku, SIM, VoLTE support and my Vodafone SIM1. VoLTE and VoWIFI can be switched on, but IMS status stays unregistered.

**Comment by basq2** [comment]
this logcat messages may help:

07-01 15:24:48.435  2747  3328 I QImsService: ImsService : enableIms :: slotId=0
07-01 15:24:48.436  2747  2853 I QImsService: ImsRadioResponse : Got registration change response from ImsRadio.
07-01 15:24:48.436  2747  2853 I QImsService: IFRequest : [0191]< REQUEST_IMS_REG_STATE_CHANGE error: 2
07-01 15:24:48.436  2747  3328 I QImsService: ImsSenderRxr : [0192]> REQUEST_IMS_REG_STATE_CHANGE [SUB0]
07-01 15:24:48.436  2747  3328 I QImsService: ImsSenderRxr : REQUEST_IMS_REG_STATE_CHANGE request to ImsRadio - token:192 RegState1
07-01 15:24:48.437  2747  2853 I QImsService: ImsRadioResponse : Got registration change response from ImsRadio.
07-01 15:24:48.438  2747  2853 I QImsService: IFRequest : [0192]< REQUEST_IMS_REG_STATE_CHANGE error: 2
07-01 15:24:48.443  8161  8173 D Service : transact: uid=10581, descriptor=com.android.internal.telephony.ITelephony, code=169
07-01 15:24:48.445  8161  8173 D Service : transact: uid=10581, descriptor=com.android.internal.telephony.ISub, code=27
07-01 15:24:48.454  2747  2747 I QImsService: ImsServiceSubHandler : Message received: what = 9
07-01 15:24:48.454  2747  2747 I QImsService: ImsServiceSub : [0] Request turn on/off IMS failed
07-01 15:24:48.454  2747  2747 I QImsService: ImsServiceSubHandler : Message received: what = 9
07-01 15:24:48.454  2747  2747 I QImsService: ImsServiceSub : [0] Request turn on/off IMS failed
07-01 15:24:48.454  2747  2747 D CarrierConfigLoader: mHandler: 16 phoneId: 0
07-01 15:24:48.455  2747  2747 D CarrierConfigLoader: Broadcast CARRIER_CONFIG_CHANGED for phone 0

**Comment by xhding1997** [comment]
> Sony XZ2 Compact latest stock Android 10. I have tried this version and running, it detects Shizuku, SIM, VoLTE support and my Vodafone SIM1. VoLTE and VoWIFI can be switched on, but IMS status stays unregistered.

same problem, i'm using OP8 Pro with Android 10. IMS status stays unregistered. Have you solved this?

**Comment by xhding1997** [comment]
> > I can confirm the modified app runs properly now on my Nokia 7 Plus. I am able to toggle both VoLTE and VoWiFi, though IMS status shows as unregistered and neither actually work. I am unsure if this is because my device is outright incompatible with my carrier's network or if it's due to how the carrier allows or blocks devices it doesn't officially support (notably my carrier only officially supports devices sold in my country). I do not expect help with this issue, but it is good to at least know the issue preventing the app from even running has been fixed.
> 
> [@karashata](https://github.com/karashata) First of all, thank you very much for your feedback. I only replaced the APIs to a lower version, and I’m not very familiar with some of the lower-level reasons. Indeed, whether volte or vowifi can be enabled also depends on the carrier, so we’ll just have to wait for others’ feedback.

Same problem, i'm using OP8 Pro with Android 10.
Shizuku, SIM, VoLTE support, VoLTE and VoWIFI can be switched on, but IMS status stays unregistered.

**Comment by kyujin-cho** [comment]
Closing as off-topic.
